language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: KNQ/Q+n8owpPC1+M/Jaww8NTpX9tsK+vU0hXdla5JIJyLAjgFGSyATGJrORvMjJv01x4yNLqscG3QMFAEl9xMpM8aUTF6VaLuo4MVaipnr01Mh3jorrPGBA7YjkL8P7SINi0qjMCGEiHYi9pAqDfaXTencJWqn2+t5hg6OZuVxA=
  - secure: qI3OdDXFFutwyfg5yrw4jxgM3nVR4T1jhpxpxl7T08nZJDzbHN227yaGg4L6ubVGAIEo1ykmpOOmGG0q0Slq9/oVmonq+B97gne2SBE7D2zoa6HpbN1x5FPrVUrsUhSF/kDzYrCEf44t7T/+pwb9AMRWgngEFbRQExR6SzbVRxQ=
  - secure: nGALs/8ellHn4mOXnoftMlJulH6jmbs9JL7D+clfOkyCJNFtARsfPKsaDAb/bYnDroFspl2TS/Z56Hz9U4H6gt2rruhIFQhElhSDLXMOk9pSh6o71azxuQBIbptC+BrJp5JCGoEqaG31Oj90WOu/N3l1Uoo+EBj1Uzv9BdV9TLE=
notifications:
  slack:
    secure: ODkEphLF2/F8jtDUCmMuZW36AUN0VofLJ7BTcI4XRqgDL4mOOhIIV26ln+Bfxw2nOe9gowTWHEQSGR6HzaS/GAQqekhY/se7AUQNIwnGtQG9E/isSRMWsni0/TM6/7Jx3WxOGxOnhfF7DkB9egY4Ih+qV3lJC2k4NAKDSV/d7Bg=
